name: Deploy to Github Pages

on:
  push:
    branches: [main]

env:
  NODE_VERSION: '___NODE_VERSION___'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "deploy nextjs app to ghpages"

    steps:
      - uses: actions/checkout@v2

      - name: use node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: build
        run: |
          npm install -g
          npm run build 
          npm run env -- next export -o build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
     
      - name: Enable GitHub Pages
        uses: actions/github-script@v4
        with:
          script: |
            const octokit = new Octokit({ auth: "${{ github.token }}" });
            await octokit.request('POST /repos/{owner}/{repo}/pages', {
              owner: '${{ github.repository_owner }}',
              repo: '${{ github.event.repository.name }}',
              source: {
                branch: 'gh-pages',
                path: '/'
              },
              mediaType: {
                previews: [
                  'switcheroo'
                ]
              }
            })
            
      - name: Website URL
        run: echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        
