name: "provision stack build/ deploy for ghpages"

on:
  workflow_dispatch:
    inputs:
      LICENSE:
        required: true
        description: 'license to be used'

      NODE_VERSION:
        required: true
        description: 'nodejs version to be used'

jobs:
  stack-initialization:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: use node.js ${{ github.event.inputs.NODE_VERSION }} 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ github.event.inputs.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: substitute variables
        run: |
          year="$(date +'%Y')"
          echo "YEAR=$year" >> $GITHUB_ENV

      - name: substitute user inputs in the workflow files
        uses: microsoft/variable-substitution@v1 
        with:
          files: '.github/workflows/deploy.yaml, .github/workflows/build.yaml'
        env:
          ___NODE_VERSION___: '${{ github.event.inputs.NODE_VERSION }}'

      - name: stacks framework code generation
        run: |
          npx create-next-app nextjs-scaffold --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/learn-starter"
          cp -r nextjs-scaffold/* .
          rm -rf nextjs-scaffold

      - name: add BSD License
        if: ${{ github.event.inputs.LICENSE == 'BSD License' }}
        run: cp ./.github/licenses/license-bsd.md LICENSE.md

      - name: add MIT License
        if: ${{ github.event.inputs.LICENSE == 'MIT License' }}
        run: cp ./.github/licenses/license-mit.md LICENSE.md

      - name: add Apache License 2.0
        if: ${{ github.event.inputs.LICENSE == 'Apache License 2.0' }}
        run: cp ./.github/licenses/license-apl.md LICENSE.md

      - name: add Mozilla Public License 2.0
        if: ${{ github.event.inputs.LICENSE == 'Mozilla Public License 2.0' }}
        run: cp ./.github/licenses/license-mpl.md LICENSE.md

      - name: add Creative Commons License
        if: ${{ github.event.inputs.LICENSE == 'Creative Commons Zero v1.0 Universal' }}
        run: cp ./.github/licenses/license-ccl.md LICENSE.md

      - name: stacks framework commit to repository
        uses: actions/github-script@v4
        with:
          script: |
            //todo: fixme the commit function/ script.

            octokit.rest.git.createCommit({
              owner,
              repo,
              message,
              tree,
              author.name,
              author.email
            })
